import { existsSync, readFileSync, statSync } from "node:fs";
import { describe, expect, it } from "vitest";

const html = readFileSync(new URL("../public/dashboard/index.html", import.meta.url), "utf8");
const app = readFileSync(new URL("../public/dashboard/app.js", import.meta.url), "utf8");
const styles = readFileSync(new URL("../public/dashboard/styles.css", import.meta.url), "utf8");
const background = new URL("../public/dashboard/background-lume.webp", import.meta.url);

describe("dashboard presentation hierarchy", () => {
  it("keeps the fleet home focused on node cards and current network quality", () => {
    expect(html).toContain('id="fleet-view"');
    expect(html).toContain('id="node-grid"');
    expect(app).not.toContain('.filter((probe) => probe.kind === "icmp")');
    expect(app).toContain("probe.packet_loss_percent");
    expect(app).toContain('metricEnergyStrip(node.id, probe, metric');
    expect(app).toContain("const ENERGY_LOSS_WARNING_PERCENT = 2");
    expect(app).toContain("const ENERGY_LOSS_CRITICAL_PERCENT = 10");
    expect(app).toContain("const ENERGY_LOSS_BURST_PERCENT = 60");
    expect(app).toContain("function energyLossSeverity");
    expect(app).toContain("row.attempted_samples");
    expect(app).toContain("row.successful_samples");
    expect(app).toContain("severeFiveMinuteLoss");
    expect(app).toContain('probeMetricCard(node, probe, "latency"');
    expect(app).toContain('probeMetricCard(node, probe, "loss"');
    expect(app).toContain('resourceGauge("CPU"');
    expect(app).toContain('resourceGauge("RAM"');
    expect(app).toContain('resourceGauge("Disk"');
    expect(app).toContain('class="node-telemetry-panel"');
    expect(app).toContain('class="node-network-row"');
    expect(app).toContain('<span>↯ 网络速率</span>');
    expect(app).not.toContain("实时速率");
    expect(app).toContain('网络质量（24H）');
    const cardTemplate = app.slice(app.indexOf("function renderNodeCard"), app.indexOf("function filteredNodes"));
    expect(cardTemplate.indexOf('class="resource-gauges"')).toBeLessThan(cardTemplate.indexOf('class="probe-block"'));
    expect(html).toContain('class="scene-image"');
    expect(html).toContain('src="/dashboard/background-lume.webp?v=orange-halo"');
    expect(styles).toContain("height: var(--scene-lock-height, 100lvh)");
    expect(styles).toContain("object-fit: cover");
    expect(styles).toContain("contain: strict");
    expect(styles).not.toContain('background-image: url("/dashboard/background-lume.webp?v=orange-halo")');
    expect(styles).not.toContain("transform: scale(1.22)");
    expect(statSync(background).size).toBeLessThan(500_000);
    expect(existsSync(new URL("../public/dashboard/background-alpine.webp", import.meta.url))).toBe(false);
    expect(styles).toContain(".node-card:hover { transform: none; }");
    expect(styles).not.toContain(".node-card:hover { transform: none; border-color:");
    expect(styles).toContain("--scene-filter: brightness(68%) contrast(106%) saturate(78%)");
    expect(styles).toContain("--scene-filter: brightness(112%) contrast(58%) saturate(48%)");
    expect(styles).toContain("--scene-scrim: rgba(0, 0, 0, 0.18)");
    expect(styles).toContain("--glass-panel-bg: rgba(7, 8, 10, 0.22)");
    expect(styles).toContain("--glass-border: rgba(255, 255, 255, 0.035)");
    expect(styles).toContain("--glass-shadow: 0 24px 66px rgba(0, 0, 0, 0.22), 0 6px 18px rgba(0, 0, 0, 0.1)");
    expect(styles).toContain("--glass-card-bg: rgba(5, 6, 8, 0.18)");
    expect(html).toContain('class="loading-ridge"');
    expect(html).toContain('class="loading-progress"');
    expect(html).toContain('aria-busy="true"');
    expect(html).not.toContain('class="loader-orbit"');
    expect(styles).toContain("@keyframes ridge-reveal");
    expect(styles).toContain("@keyframes horizon-travel");
    expect(styles).toContain("z-index: 0;");
    expect(styles).toContain("--quality-good: #5bdda9");
    expect(styles).toContain(".probe-metric.is-latency, .probe-metric.is-loss { --metric-color: var(--quality-good); }");
    expect(styles).toContain(".energy-strip { --energy-color: var(--quality-good);");
    expect(styles).not.toContain(".energy-strip { --energy-color: var(--metric-color");
    expect(styles).toContain(".node-network-row > strong { font-size: 16px; }");
    expect(html).toContain('id="node-search"');
    expect(html).not.toContain('id="node-filter"');
    expect(html).toContain('class="fleet-toolbar"');
    expect(html).not.toContain('class="fleet-toolbar glass-panel"');
    expect(app).not.toContain("state.filter");
    expect(styles).toContain(".node-network-row > strong { gap: 8px; font-size: 13px; }");
    const glassRule = styles.slice(styles.indexOf(".glass-panel {"), styles.indexOf(".brand-lockup"));
    const nodeCardRule = styles.slice(styles.indexOf(".node-card {"), styles.indexOf(".node-card.is-warning"));
    expect(glassRule).not.toContain("gradient");
    expect(nodeCardRule).not.toContain("gradient");
    expect(glassRule).toContain("background: var(--glass-panel-bg)");
    expect(glassRule).toContain("backdrop-filter: var(--glass-filter)");
    expect(nodeCardRule).toContain("background: var(--glass-card-bg)");
    expect(nodeCardRule).toContain("backdrop-filter: var(--glass-filter)");
    expect(glassRule).not.toContain("grayscale(");
    expect(nodeCardRule).not.toContain("grayscale(");
    expect(nodeCardRule).not.toContain("rgba(10, 18, 29");
    expect(styles).toContain('html[data-theme="light"]');
    expect(styles).toContain("--scene-scrim: rgba(239, 245, 251, 0.22)");
    expect(styles).toContain("--glass-panel-bg: rgba(255, 255, 255, 0.035)");
    expect(styles).toContain("--glass-border: rgba(255, 255, 255, 0.055)");
    expect(styles).toContain("--glass-card-bg: rgba(255, 255, 255, 0.03)");
    expect(styles).toContain("--glass-filter: blur(16px) saturate(106%) brightness(112%)");
    expect(styles).not.toContain("rgba(244, 248, 252, 0.46)");
    expect(styles).toContain("--glass-tooltip-bg: rgba(255, 255, 255, 0.09)");
    expect(styles).toContain(".plot-tooltip");
    expect(html).toContain('<svg viewBox="0 0 24 24" aria-hidden="true">');
    expect(html).not.toContain(">⚙</button>");
    expect(styles).toContain("Desktop readability: keep display headings unchanged");
    expect(app).toContain("const FLAG_ART");
    expect(app).toContain('class="node-uptime"');
    expect(app).toContain('class="detail-service-list"');
    const resourceGaugeTemplate = app.slice(app.indexOf("function resourceGauge"), app.indexOf("function detailServiceList"));
    expect(resourceGaugeTemplate).not.toContain("style=");
    expect(app).toContain('class="resource-gauge-track"');
    expect(app).toContain('class="resource-gauge-fill"');
    expect(app).toContain('stroke-dasharray="${level} ${gap}"');
    expect(app).toContain('const fill = numeric <= 0.05 ? ""');
    expect(app).toContain('class="resource-gauge-marker" cx="${level}%"');
    expect(app).toContain('class="resource-threshold resource-threshold-warning" x1="70%"');
    expect(app).toContain('class="resource-threshold resource-threshold-critical" x1="85%"');
    expect(styles).toContain("--gauge-color: var(--green)");
    expect(styles).toContain(".resource-gauge-base, .resource-gauge-fill");
    expect(styles).toContain("stroke-linecap: round");
    expect(styles).not.toContain(".resource-ring");
    expect(styles).not.toContain(".resource-progress");
    const healthyCard = app.slice(app.indexOf('const probes = displayProbes(node);'), app.indexOf("function filteredNodes"));
    expect(healthyCard).not.toContain("service.label");
    expect(healthyCard).not.toContain("service.text");
    expect(healthyCard).not.toContain("loadSummary");
  });

  it("keeps history charts in an independent node detail view", () => {
    expect(html).toContain('id="node-detail" class="detail-view is-hidden"');
    expect(html).toContain('id="network-plot"');
    expect(html).toContain('id="detail-probe-actions"');
    expect(html).toContain('data-network-layer="latency"');
    expect(html).toContain('data-network-layer="loss"');
    expect(html).not.toContain('id="resource-plot"');
    expect(html).toContain('id="traffic-plot"');
    expect(html).toContain('<p class="eyebrow">NETWORK ACTIVITY</p><h2>网络速率</h2>');
    expect(html).not.toContain('HOST TELEMETRY');
    expect(app).not.toContain('class="detail-mini-gauges"');
    expect(app).toContain('class="detail-flag" role="img"');
    expect(app).toContain("${flagIcon(node.country)}");
    expect(app).toContain('JP: `<svg viewBox="0 0 36 24"');
    expect(app).not.toContain("node.mark || flagEmoji");
    expect(app).not.toContain('detailFact("实时下载"');
    expect(app).not.toContain('detailFact("实时上传"');
    expect(app).toContain('detailFact("下载速率"');
    expect(app).toContain('detailFact("上传速率"');
    expect(html).toContain("<strong>速率历史</strong>");
    expect(app).toContain('$("fleet-view").classList.add("is-hidden")');
    expect(app).toContain('new window.uPlot');
    expect(app).toContain('data-detail-probe=');
    expect(app).toContain('state.detailProbeSelection.has(probe.name)');
    expect(app).toContain("networkLossMarkersPlugin");
    expect(app).toContain("networkTooltipPlugin");
    expect(app).toContain("metricTooltipPlugin");
    expect(app).toContain("smoothSeriesPath");
    expect(app).toContain("window.uPlot.paths.spline()");
    expect(app).toContain('class="detail-probe-swatch"');
    expect(app).toContain('class="detail-probe-card probe-tone-${tone}');
    expect(app).toContain("PROBE_COLOR_VARIABLES[probeColorTone(probe)]");
    expect(app).not.toContain('style="--probe-color:');
    expect(app).not.toContain('class="detail-probe-swatch" style=');
    expect(app).toContain("focus: { prox: 6 }");
    expect(app).not.toContain("focus: { prox: 36 }");
    expect(app).toContain('legend: { show: false }');
    expect(app).toContain('function fleetHistoryPreview(nodeId, hours)');
    expect(app).toContain('state.detailHistoryCache.get(detailHistoryKey(nodeId, hours))');
    expect(app).toContain('void loadDetailHistory({ background: Boolean(state.detailHistory) })');
    expect(app).toContain('state.detailHistoryRequests.set(key, request)');
    expect(app).toContain('replace(/\\s*状态\\s*$/u');
    expect(app).not.toContain("node.source_ip");
    expect(app).not.toContain("node.source_asn");
    expect(app).not.toContain("上报源 IPv4");
    expect(app).not.toContain("上报源 IPv6");
    expect(app).not.toContain('detailFact("ASN"');
    expect(styles).toContain(".plot-tooltip");
    expect(styles).toContain("--probe-telecom");
    expect(styles).toContain(".detail-probe-card { --probe-color: var(--probe-link); display: grid;");
    const probeCardRule = styles.slice(styles.indexOf(".detail-probe-card {"), styles.indexOf(".detail-probe-card::before"));
    expect(probeCardRule).toContain("border: 1px solid var(--glass-border)");
    expect(probeCardRule).toContain("border-radius: 8px");
    expect(probeCardRule).not.toContain("inset");
    expect(styles).toContain("grid-template-columns: repeat(2, minmax(0, 1fr))");
    expect(html).toContain('class="chart-series-key"');
    expect(html).toContain('class="probe-picker"');
    expect(html).not.toContain('class="probe-picker glass-panel"');
    expect(styles).toContain('.detail-probe-card::before { content: none; }');
    expect(styles).toContain(".detail-probe-swatch { display: block !important; width: 8px; height: 26px;");
    expect(styles).toContain(".detail-probe-card.probe-tone-telecom { --probe-color: var(--probe-telecom); }");
    expect(styles).toContain(".detail-probe-card.probe-tone-unicom { --probe-color: var(--probe-unicom); }");
    expect(styles).toContain(".detail-probe-card.probe-tone-mobile { --probe-color: var(--probe-mobile); }");
    expect(styles).toContain(".detail-probe-card.probe-tone-link { --probe-color: var(--probe-link); }");
    expect(styles).toContain(".probe-picker-actions button { min-height: 34px;");
    expect(styles).toContain(".detail-probe-summary { grid-template-columns: repeat(2, minmax(0, 1fr)); overflow: visible;");
    expect(styles).toContain(".detail-probe-card > span:not(.detail-probe-label) { display: none; }");
    expect(html).toContain("<h2>延迟与丢包</h2>");
    expect(html).not.toContain("延迟与丢包趋势");
    expect(html).not.toContain("点击目标卡片显示或隐藏");
    expect(html).not.toContain("资源与网络速率仅在详情中展示历史");
    expect(html).not.toContain("只监控，不自动切换线路或远程控制节点");
    expect(html).toContain("<h2>事件</h2>");
    expect(html).not.toContain("<h2>区间事件</h2>");
    expect(styles).toContain("--probe-unicom: #f26f8f");
    expect(styles).toContain('html[data-theme="light"] .search-control');
    expect(styles).toContain('html[data-theme="light"] .range-switch');
    expect(styles).toContain('.detail-probe-card.is-active');
    expect(styles).toContain('html[data-theme="light"] .detail-probe-card');
  });

  it("uses one compact glass edge for cards, search and time controls", () => {
    const searchRule = styles.slice(styles.indexOf(".search-control {"), styles.indexOf(".search-control > svg"));
    const rangeRule = styles.slice(styles.indexOf(".range-switch { padding:"), styles.indexOf(".range-switch button { min-width"));
    const nodeCardRule = styles.slice(styles.indexOf(".node-card {"), styles.indexOf(".node-card:focus"));
    expect(styles).toContain("--radius-xl: 16px");
    expect(styles).toContain("--radius-lg: 14px");
    expect(searchRule).toContain("border-radius: 8px");
    expect(searchRule).not.toContain("inset");
    expect(rangeRule).toContain("border-radius: 9px");
    expect(rangeRule).not.toContain("inset");
    expect(nodeCardRule).toContain("border-radius: 16px");
  });

  it("loads the pinned chart library locally instead of from a CDN", () => {
    expect(html).toContain('/dashboard/styles.css?v=1.1.0&amp;b=stable-scene-v2');
    expect(html).toContain('/dashboard/app.js?v=1.1.0&amp;b=stable-scene-v2');
    expect(html).toContain('/dashboard/vendor/uPlot.iife.min.js');
    expect(html).toContain('/dashboard/vendor/uPlot.min.css');
    expect(html).not.toMatch(/https?:\/\/[^\s"']+u[Pp]lot/);
  });

  it("shows the actual probe cadence instead of a stale fixed interval", () => {
    expect(app).toContain("state.latest?.cadence?.probes_seconds ?? 60");
    expect(app).toContain("formatInterval");
    expect(app).not.toContain('["探针周期", "5 分钟"');
  });

  it("supports local-only dashboard and node display customization", () => {
    expect(html).toContain('id="settings-button"');
    expect(html).toContain('id="settings-dialog"');
    expect(html).toContain('id="settings-node-list"');
    expect(html).toContain('id="settings-brand"');
    expect(html).not.toContain('id="settings-page-title"');
    expect(html).not.toContain('id="settings-page-subtitle"');
    expect(app).toContain('const DASHBOARD_LAYOUT_KEY = "vpsmon-dashboard-layout-v1"');
    expect(app).toContain("localStorage.setItem");
    expect(app).toContain("state.settingsDraftOrder");
    expect(app).toContain("applyNodeLayout");
    expect(app).not.toContain('fetch("/api/v1/dashboard/settings"');
  });

  it("uses the Lume identity without the redundant fleet heading", () => {
    expect(html).toContain("<title>Lume</title>");
    expect(html).not.toContain("远山不见我，而我见远山");
    expect(app).toContain('brand: "Lume"');
    expect(html).not.toContain("节点总览");
    expect(html).not.toContain("LIVE FLEET");
    expect(html).not.toContain("当前状态、线路延迟、丢包与资源占用。");
    const dashboardHeader = html.slice(html.indexOf('<header class="command-bar glass-panel">'), html.indexOf('<main class="page-shell">'));
    expect(dashboardHeader).not.toContain('class="brand-mark"');
    expect(styles).toContain(".node-status .node-live-dot { flex: 0 0 6px; background-color: var(--green);");
  });

  it("locks the background canvas against mobile browser chrome resizing", () => {
    expect(app).toContain("function usesStableTouchViewport");
    expect(app).toContain("function lockSceneViewport");
    expect(app).toContain("function scheduleSceneViewportLock");
    expect(app).toContain('window.addEventListener("orientationchange"');
    expect(app).not.toContain('visualViewport.addEventListener("resize"');
    expect(app).not.toContain('visualViewport.addEventListener("scroll"');
  });

  it("uses full-bleed glass chrome while preserving the existing content", () => {
    expect(html).toContain('class="command-bar glass-panel"');
    expect(styles).toContain("width: calc(100% + 36px)");
    expect(styles).toContain("margin: 0 -18px");
    const commandRule = styles.slice(styles.indexOf(".command-bar {"), styles.indexOf(".fleet-health {"));
    expect(commandRule).toContain("border: 0");
    expect(commandRule).toContain("border-radius: 0");
    expect(commandRule).toContain("background: var(--glass-chrome-bg)");
    expect(styles).toContain(".dashboard-footer { position: relative; isolation: isolate; display: block; width: calc(100% + 36px)");
    expect(styles).toContain("margin: 56px -18px 0");
    expect(styles).toContain("border: 0; background: transparent; box-shadow: none");
    expect(styles).toContain(".dashboard-footer::before { content: \"\";");
    expect(styles).toContain("background: var(--glass-footer-bg)");
    expect(styles).toContain("mask-image: linear-gradient(to bottom, transparent, #000 38px)");
    expect(styles).toContain("min-height: 112px");
    expect(html).toContain('<footer class="dashboard-footer" aria-hidden="true"></footer>');
    expect(html).not.toContain("footer-motto");
  });
});
