import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const html = readFileSync(new URL("../public/dashboard/index.html", import.meta.url), "utf8");
const app = readFileSync(new URL("../public/dashboard/app.js", import.meta.url), "utf8");
const styles = readFileSync(new URL("../public/dashboard/styles.css", import.meta.url), "utf8");

describe("dashboard presentation hierarchy", () => {
  it("keeps the fleet home focused on node cards and current network quality", () => {
    expect(html).toContain('id="fleet-view"');
    expect(html).toContain('id="node-grid"');
    expect(app).toContain('.filter((probe) => probe.kind === "icmp")');
    expect(app).toContain("probe.packet_loss_percent");
    expect(app).toContain('metricEnergyStrip(node.id, probe, metric');
    expect(app).toContain('probeMetricCard(node, probe, "latency"');
    expect(app).toContain('probeMetricCard(node, probe, "loss"');
    expect(app).toContain('resourceGauge("CPU"');
    expect(app).toContain('resourceGauge("RAM"');
    expect(app).toContain('resourceGauge("SSD"');
    expect(app).toContain('class="node-telemetry-panel"');
    expect(app).toContain('class="node-network-row"');
    expect(app).toContain('网络质量（24H）');
    const cardTemplate = app.slice(app.indexOf("function renderNodeCard"), app.indexOf("function filteredNodes"));
    expect(cardTemplate.indexOf('class="resource-gauges"')).toBeLessThan(cardTemplate.indexOf('class="probe-block"'));
    expect(styles).toContain("backdrop-filter: blur(18px) saturate(120%)");
    expect(styles).toContain('background-image: url("/dashboard/background-alpine.webp")');
    expect(styles).toContain(".node-card:hover { transform: none;");
    expect(styles).toContain("background: rgba(10, 18, 29, 0.14)");
    expect(styles).toContain("z-index: 0;");
    expect(styles).toContain("--quality-good: #5bdda9");
    expect(styles).toContain(".probe-metric.is-latency, .probe-metric.is-loss { --metric-color: var(--quality-good); }");
    expect(styles).toContain(".energy-strip { --energy-color: var(--quality-good);");
    expect(styles).not.toContain(".energy-strip { --energy-color: var(--metric-color");
    expect(styles).toContain(".node-network-row > strong { font-size: 16px; }");
    expect(html).toContain('id="node-search"');
    expect(html).not.toContain('id="node-filter"');
    expect(html).toContain('class="fleet-toolbar"');
    expect(html).not.toContain('class="fleet-toolbar glass-panel"');
    expect(app).not.toContain("state.filter");
    expect(styles).toContain(".node-network-row > strong { gap: 8px; font-size: 13px; }");
    const glassRule = styles.slice(styles.indexOf(".glass-panel {"), styles.indexOf(".brand-lockup"));
    const nodeCardRule = styles.slice(styles.indexOf(".node-card {"), styles.indexOf(".node-card.is-warning"));
    expect(glassRule).not.toContain("gradient");
    expect(nodeCardRule).not.toContain("gradient");
    expect(styles).toContain("Desktop readability: keep display headings unchanged");
    expect(app).toContain("const FLAG_ART");
    expect(app).toContain('class="node-uptime"');
    expect(app).toContain('class="detail-service-list"');
    expect(app).toContain('class="resource-track"');
    expect(app).toContain('class="resource-value"');
    expect(app).toContain('stroke-dasharray="${numeric.toFixed(1)} ${(100 - numeric).toFixed(1)}"');
    expect(styles).toContain("--gauge-color: var(--green)");
    expect(styles).toContain("stroke-linecap: round");
    expect(styles).not.toContain("@keyframes gauge-progress");
    expect(styles).not.toContain(".resource-ring::before");
    expect(styles).not.toContain("stroke-dasharray: calc(var(--value)");
    expect(styles).not.toContain("background: conic-gradient(from -90deg");
    const healthyCard = app.slice(app.indexOf('const probes = displayProbes(node);'), app.indexOf("function filteredNodes"));
    expect(healthyCard).not.toContain("service.label");
    expect(healthyCard).not.toContain("service.text");
    expect(healthyCard).not.toContain("loadSummary");
  });

  it("keeps history charts in an independent node detail view", () => {
    expect(html).toContain('id="node-detail" class="detail-view is-hidden"');
    expect(html).toContain('id="network-plot"');
    expect(html).toContain('id="detail-probe-actions"');
    expect(html).toContain('data-network-layer="latency"');
    expect(html).toContain('data-network-layer="loss"');
    expect(html).toContain('id="resource-plot"');
    expect(html).toContain('id="traffic-plot"');
    expect(app).toContain('$("fleet-view").classList.add("is-hidden")');
    expect(app).toContain('new window.uPlot');
    expect(app).toContain('data-detail-probe=');
    expect(app).toContain('state.detailProbeSelection.has(probe.name)');
    expect(app).toContain("networkLossMarkersPlugin");
    expect(app).toContain("networkTooltipPlugin");
    expect(app).toContain("metricTooltipPlugin");
    expect(app).toContain("smoothSeriesPath");
    expect(app).toContain("window.uPlot.paths.spline()");
    expect(app).toContain('class="detail-probe-swatch"');
    expect(app).toContain('class="detail-probe-card probe-tone-${tone}');
    expect(app).toContain("PROBE_COLOR_VARIABLES[probeColorTone(probe)]");
    expect(app).not.toContain('style="--probe-color:');
    expect(app).not.toContain('class="detail-probe-swatch" style=');
    expect(app).toContain("focus: { prox: 6 }");
    expect(app).not.toContain("focus: { prox: 36 }");
    expect(app).toContain('legend: { show: false }');
    expect(app).toContain('replace(/\\s*状态\\s*$/u');
    expect(app).not.toContain("node.source_ip");
    expect(app).not.toContain("node.source_asn");
    expect(app).not.toContain("上报源 IPv4");
    expect(app).not.toContain("上报源 IPv6");
    expect(app).not.toContain('detailFact("ASN"');
    expect(styles).toContain(".plot-tooltip");
    expect(styles).toContain("--probe-telecom");
    expect(styles).toContain(".detail-probe-card { --probe-color: var(--probe-link); display: grid;");
    expect(styles).toContain("border: 0;");
    expect(styles).toContain("grid-template-columns: repeat(2, minmax(0, 1fr))");
    expect(html).toContain('class="chart-series-key"');
    expect(html).toContain('class="probe-picker"');
    expect(html).not.toContain('class="probe-picker glass-panel"');
    expect(styles).toContain('.detail-probe-card::before { content: none; }');
    expect(styles).toContain(".detail-probe-swatch { display: block !important; width: 8px; height: 26px;");
    expect(styles).toContain(".detail-probe-card.probe-tone-telecom { --probe-color: var(--probe-telecom); }");
    expect(styles).toContain(".detail-probe-card.probe-tone-unicom { --probe-color: var(--probe-unicom); }");
    expect(styles).toContain(".detail-probe-card.probe-tone-mobile { --probe-color: var(--probe-mobile); }");
    expect(styles).toContain(".detail-probe-card.probe-tone-link { --probe-color: var(--probe-link); }");
    expect(styles).toContain(".probe-picker-actions button { min-height: 34px;");
    expect(styles).toContain("grid-auto-columns: minmax(240px, 82%)");
    expect(html).toContain("<h2>延迟与丢包</h2>");
    expect(html).not.toContain("延迟与丢包趋势");
    expect(html).not.toContain("点击目标卡片显示或隐藏");
    expect(html).not.toContain("资源与网络速率仅在详情中展示历史");
    expect(html).not.toContain("只监控，不自动切换线路或远程控制节点");
    expect(html).toContain("<h2>事件</h2>");
    expect(html).not.toContain("<h2>区间事件</h2>");
    expect(styles).toContain("--probe-unicom: #f26f8f");
    expect(styles).toContain('html[data-theme="light"] .search-control');
    expect(styles).toContain('html[data-theme="light"] .range-switch');
    expect(styles).toContain('html[data-theme="light"] .detail-probe-card.is-active');
  });

  it("loads the pinned chart library locally instead of from a CDN", () => {
    expect(html).toContain('/dashboard/styles.css?v=1.0.0&amp;b=history-1m');
    expect(html).toContain('/dashboard/app.js?v=1.0.0&amp;b=history-1m');
    expect(html).toContain('/dashboard/vendor/uPlot.iife.min.js');
    expect(html).toContain('/dashboard/vendor/uPlot.min.css');
    expect(html).not.toMatch(/https?:\/\/[^\s"']+u[Pp]lot/);
  });

  it("shows the actual probe cadence instead of a stale fixed interval", () => {
    expect(app).toContain("state.latest?.cadence?.probes_seconds ?? 60");
    expect(app).toContain("formatInterval");
    expect(app).not.toContain('["探针周期", "5 分钟"');
  });

  it("supports local-only dashboard and node display customization", () => {
    expect(html).toContain('id="settings-button"');
    expect(html).toContain('id="settings-dialog"');
    expect(html).toContain('id="settings-node-list"');
    expect(html).toContain('id="settings-brand"');
    expect(html).not.toContain('id="settings-page-title"');
    expect(html).not.toContain('id="settings-page-subtitle"');
    expect(app).toContain('const DASHBOARD_LAYOUT_KEY = "vpsmon-dashboard-layout-v1"');
    expect(app).toContain("localStorage.setItem");
    expect(app).toContain("state.settingsDraftOrder");
    expect(app).toContain("applyNodeLayout");
    expect(app).not.toContain('fetch("/api/v1/dashboard/settings"');
  });

  it("uses the 远山Monitor identity without the redundant fleet heading", () => {
    expect(html).toContain("<title>远山Monitor</title>");
    expect(html).toContain("远山不见我，而我见远山");
    expect(app).toContain('brand: "远山Monitor"');
    expect(html).not.toContain("节点总览");
    expect(html).not.toContain("LIVE FLEET");
    expect(html).not.toContain("当前状态、线路延迟、丢包与资源占用。");
    expect(styles).toContain(".node-status .node-live-dot { flex: 0 0 6px; background-color: var(--green);");
  });
});
